package com.anyware.esolutions.emoji_library.emoji;

public class Flags {

    public static final Emojicon[] DATA = new Emojicon[]{

            //Maps

            Emojicon.fromCodePoint(0x1a1a0),
            Emojicon.fromCodePoint(0x1a1a1),
            Emojicon.fromCodePoint(0x1a1a2),
            Emojicon.fromCodePoint(0x1a1a3),
            Emojicon.fromCodePoint(0x1a1a4),
            Emojicon.fromCodePoint(0x1a1a5),
            Emojicon.fromCodePoint(0x1a1a6),
            Emojicon.fromCodePoint(0x1a1a7),
            Emojicon.fromCodePoint(0x1a1a8),
            Emojicon.fromCodePoint(0x1a1a9),

            Emojicon.fromCodePoint(0x1a1b0),
            Emojicon.fromCodePoint(0x1a1b1),
            Emojicon.fromCodePoint(0x1a1b2),
            Emojicon.fromCodePoint(0x1a1b3),
            Emojicon.fromCodePoint(0x1a1b4),
            Emojicon.fromCodePoint(0x1a1b5),
            Emojicon.fromCodePoint(0x1a1b6),
            Emojicon.fromCodePoint(0x1a1b7),
            Emojicon.fromCodePoint(0x1a1b8),
            Emojicon.fromCodePoint(0x1a1b9),

            Emojicon.fromCodePoint(0x1a1c0),
            Emojicon.fromCodePoint(0x1a1c1),
            Emojicon.fromCodePoint(0x1a1c2),
            Emojicon.fromCodePoint(0x1a1c3),
            Emojicon.fromCodePoint(0x1a1c4),
            Emojicon.fromCodePoint(0x1a1c5),
            Emojicon.fromCodePoint(0x1a1c6),
            Emojicon.fromCodePoint(0x1a1c7),
            Emojicon.fromCodePoint(0x1a1c8),
            Emojicon.fromCodePoint(0x1a1c9),

            Emojicon.fromCodePoint(0x1a1d0),
            Emojicon.fromCodePoint(0x1a1d1),
            Emojicon.fromCodePoint(0x1a1d2),
            Emojicon.fromCodePoint(0x1a1d3),
            Emojicon.fromCodePoint(0x1a1d4),
            Emojicon.fromCodePoint(0x1a1d5),
            Emojicon.fromCodePoint(0x1a1d6),
            Emojicon.fromCodePoint(0x1a1d7),
            Emojicon.fromCodePoint(0x1a1d8),
            Emojicon.fromCodePoint(0x1a1d9),

            Emojicon.fromCodePoint(0x1a1e0),
            Emojicon.fromCodePoint(0x1a1e1),
            Emojicon.fromCodePoint(0x1a1e2),
            Emojicon.fromCodePoint(0x1a1e3),
            Emojicon.fromCodePoint(0x1a1e4),
            Emojicon.fromCodePoint(0x1a1e5),
            Emojicon.fromCodePoint(0x1a1e6),
            Emojicon.fromCodePoint(0x1a1e7),
            Emojicon.fromCodePoint(0x1a1e8),
            Emojicon.fromCodePoint(0x1a1e9),

            Emojicon.fromCodePoint(0x1a1f0),
            Emojicon.fromCodePoint(0x1a1f1),
            Emojicon.fromCodePoint(0x1a1f2),
            Emojicon.fromCodePoint(0x1a1f3),
            Emojicon.fromCodePoint(0x1a1f4),
            Emojicon.fromCodePoint(0x1a1f5),
            Emojicon.fromCodePoint(0x1a1f6),
            Emojicon.fromCodePoint(0x1a1f7),
            Emojicon.fromCodePoint(0x1a1f8),
            Emojicon.fromCodePoint(0x1a1f9),

            Emojicon.fromCodePoint(0x1a2a0),
            Emojicon.fromCodePoint(0x1a2a1),
            Emojicon.fromCodePoint(0x1a2a2),
            Emojicon.fromCodePoint(0x1a2a3),
            Emojicon.fromCodePoint(0x1a2a4),
            Emojicon.fromCodePoint(0x1a2a5),
            Emojicon.fromCodePoint(0x1a2a6),
            Emojicon.fromCodePoint(0x1a2a7),
            Emojicon.fromCodePoint(0x1a2a8),
            Emojicon.fromCodePoint(0x1a2a9),

            Emojicon.fromCodePoint(0x1a2b0),
            Emojicon.fromCodePoint(0x1a2b1),
            Emojicon.fromCodePoint(0x1a2b2),
            Emojicon.fromCodePoint(0x1a2b3),
            Emojicon.fromCodePoint(0x1a2b4),
            Emojicon.fromCodePoint(0x1a2b5),
            Emojicon.fromCodePoint(0x1a2b6),
            Emojicon.fromCodePoint(0x1a2b7),
            Emojicon.fromCodePoint(0x1a2b8),
            Emojicon.fromCodePoint(0x1a2b9),

            Emojicon.fromCodePoint(0x1a2c0),
            Emojicon.fromCodePoint(0x1a2c1),
            Emojicon.fromCodePoint(0x1a2c2),
            Emojicon.fromCodePoint(0x1a2c3),
            Emojicon.fromCodePoint(0x1a2c4),
            Emojicon.fromCodePoint(0x1a2c5),
            Emojicon.fromCodePoint(0x1a2c6),
            Emojicon.fromCodePoint(0x1a2c7),
            Emojicon.fromCodePoint(0x1a2c8),
            Emojicon.fromCodePoint(0x1a2c9),

            Emojicon.fromCodePoint(0x1a2d0),
            Emojicon.fromCodePoint(0x1a2d1),
            Emojicon.fromCodePoint(0x1a2d2),
            Emojicon.fromCodePoint(0x1a2d3),
            Emojicon.fromCodePoint(0x1a2d4),
            Emojicon.fromCodePoint(0x1a2d5),
            Emojicon.fromCodePoint(0x1a2d6),
            Emojicon.fromCodePoint(0x1a2d7),
            Emojicon.fromCodePoint(0x1a2d8),
            Emojicon.fromCodePoint(0x1a2d9),

            Emojicon.fromCodePoint(0x1a2e0),
            Emojicon.fromCodePoint(0x1a2e1),
            Emojicon.fromCodePoint(0x1a2e2),
            Emojicon.fromCodePoint(0x1a2e3),
            Emojicon.fromCodePoint(0x1a2e4),
            Emojicon.fromCodePoint(0x1a2e5),
            Emojicon.fromCodePoint(0x1a2e6),
            Emojicon.fromCodePoint(0x1a2e7),
            Emojicon.fromCodePoint(0x1a2e8),
            Emojicon.fromCodePoint(0x1a2e9),

            Emojicon.fromCodePoint(0x1a2f0),
            Emojicon.fromCodePoint(0x1a2f1),
            Emojicon.fromCodePoint(0x1a2f2),
            Emojicon.fromCodePoint(0x1a2f3),
            Emojicon.fromCodePoint(0x1a2f4),
            Emojicon.fromCodePoint(0x1a2f5),
            Emojicon.fromCodePoint(0x1a2f6),
            Emojicon.fromCodePoint(0x1a2f7),
            Emojicon.fromCodePoint(0x1a2f8),
            Emojicon.fromCodePoint(0x1a2f9),

            Emojicon.fromCodePoint(0x1a3a0),
            Emojicon.fromCodePoint(0x1a3a1),
            Emojicon.fromCodePoint(0x1a3a2),
            Emojicon.fromCodePoint(0x1a3a3),
            Emojicon.fromCodePoint(0x1a3a4),
            Emojicon.fromCodePoint(0x1a3a5),
            Emojicon.fromCodePoint(0x1a3a6),
            Emojicon.fromCodePoint(0x1a3a7),
            Emojicon.fromCodePoint(0x1a3a8),
            Emojicon.fromCodePoint(0x1a3a9),

            Emojicon.fromCodePoint(0x1a3b0),
            Emojicon.fromCodePoint(0x1a3b1),
            Emojicon.fromCodePoint(0x1a3b2),
            Emojicon.fromCodePoint(0x1a3b3),
            Emojicon.fromCodePoint(0x1a3b4),
            Emojicon.fromCodePoint(0x1a3b5),
            Emojicon.fromCodePoint(0x1a3b6),
            Emojicon.fromCodePoint(0x1a3b7),
            Emojicon.fromCodePoint(0x1a3b8),
            Emojicon.fromCodePoint(0x1a3b9),

            Emojicon.fromCodePoint(0x1a3c0),
            Emojicon.fromCodePoint(0x1a3c1),
            Emojicon.fromCodePoint(0x1a3c2),
            Emojicon.fromCodePoint(0x1a3c3),
            Emojicon.fromCodePoint(0x1a3c4),
            Emojicon.fromCodePoint(0x1a3c5),
            Emojicon.fromCodePoint(0x1a3c6),
            Emojicon.fromCodePoint(0x1a3c7),
            Emojicon.fromCodePoint(0x1a3c8),
            Emojicon.fromCodePoint(0x1a3c9),

            Emojicon.fromCodePoint(0x1a3d0),
            Emojicon.fromCodePoint(0x1a3d1),
            Emojicon.fromCodePoint(0x1a3d2),
            Emojicon.fromCodePoint(0x1a3d3),
            Emojicon.fromCodePoint(0x1a3d4),
            Emojicon.fromCodePoint(0x1a3d5),
            Emojicon.fromCodePoint(0x1a3d6),
            Emojicon.fromCodePoint(0x1a3d7),
            Emojicon.fromCodePoint(0x1a3d8),
            Emojicon.fromCodePoint(0x1a3d9),

            Emojicon.fromCodePoint(0x1a3e0),
            Emojicon.fromCodePoint(0x1a3e1),
            Emojicon.fromCodePoint(0x1a3e2),
            Emojicon.fromCodePoint(0x1a3e3),
            Emojicon.fromCodePoint(0x1a3e4),
            Emojicon.fromCodePoint(0x1a3e5),
            Emojicon.fromCodePoint(0x1a3e6),
            Emojicon.fromCodePoint(0x1a3e7),
            Emojicon.fromCodePoint(0x1a3e8),
            Emojicon.fromCodePoint(0x1a3e9),

            Emojicon.fromCodePoint(0x1a3f0),
            Emojicon.fromCodePoint(0x1a3f1),
            Emojicon.fromCodePoint(0x1a3f2),
            Emojicon.fromCodePoint(0x1a3f3),
            Emojicon.fromCodePoint(0x1a3f4),
            Emojicon.fromCodePoint(0x1a3f5),
            Emojicon.fromCodePoint(0x1a3f6),
            Emojicon.fromCodePoint(0x1a3f7),
            Emojicon.fromCodePoint(0x1a3f8),
            Emojicon.fromCodePoint(0x1a3f9),

            Emojicon.fromCodePoint(0x1a4a0),
            Emojicon.fromCodePoint(0x1a4a1),
            Emojicon.fromCodePoint(0x1a4a2),
            Emojicon.fromCodePoint(0x1a4a3),
            Emojicon.fromCodePoint(0x1a4a4),
            Emojicon.fromCodePoint(0x1a4a5),
            Emojicon.fromCodePoint(0x1a4a6),
            Emojicon.fromCodePoint(0x1a4a7),
            Emojicon.fromCodePoint(0x1a4a8),
            Emojicon.fromCodePoint(0x1a4a9),

            Emojicon.fromCodePoint(0x1a4b0),
            Emojicon.fromCodePoint(0x1a4b1),
            Emojicon.fromCodePoint(0x1a4b2),
            Emojicon.fromCodePoint(0x1a4b3),
            Emojicon.fromCodePoint(0x1a4b4),
            Emojicon.fromCodePoint(0x1a4b5),
            Emojicon.fromCodePoint(0x1a4b6),
            Emojicon.fromCodePoint(0x1a4b7),
            Emojicon.fromCodePoint(0x1a4b8),
            Emojicon.fromCodePoint(0x1a4b9),

            Emojicon.fromCodePoint(0x1a4c0),
            Emojicon.fromCodePoint(0x1a4c1),
            Emojicon.fromCodePoint(0x1a4c2),
            Emojicon.fromCodePoint(0x1a4c3),
            Emojicon.fromCodePoint(0x1a4c4),
            Emojicon.fromCodePoint(0x1a4c5),
            Emojicon.fromCodePoint(0x1a4c6),
            Emojicon.fromCodePoint(0x1a4c7),
            Emojicon.fromCodePoint(0x1a4c8),
            Emojicon.fromCodePoint(0x1a4c9),

            Emojicon.fromCodePoint(0x1a4d0),
            Emojicon.fromCodePoint(0x1a4d1),
            Emojicon.fromCodePoint(0x1a4d2),
            Emojicon.fromCodePoint(0x1a4d3),
            Emojicon.fromCodePoint(0x1a4d4),
            Emojicon.fromCodePoint(0x1a4d5),
            Emojicon.fromCodePoint(0x1a4d6),
            Emojicon.fromCodePoint(0x1a4d7),
            Emojicon.fromCodePoint(0x1a4d8),
            Emojicon.fromCodePoint(0x1a4d9),

            Emojicon.fromCodePoint(0x1a4f0),
            Emojicon.fromCodePoint(0x1a4f1),
            Emojicon.fromCodePoint(0x1a4f2),
            Emojicon.fromCodePoint(0x1a4f3),
            Emojicon.fromCodePoint(0x1a4f4),
            Emojicon.fromCodePoint(0x1a4f5),
            Emojicon.fromCodePoint(0x1a4f6),
            Emojicon.fromCodePoint(0x1a4f7),
            Emojicon.fromCodePoint(0x1a4f8),
            Emojicon.fromCodePoint(0x1a4f9),

            Emojicon.fromCodePoint(0x1a5a0),
            Emojicon.fromCodePoint(0x1a5a1),
            Emojicon.fromCodePoint(0x1a5a2),
            Emojicon.fromCodePoint(0x1a5a3),
            Emojicon.fromCodePoint(0x1a5a4),
            Emojicon.fromCodePoint(0x1a5a5),
            Emojicon.fromCodePoint(0x1a5a6),
            Emojicon.fromCodePoint(0x1a5a7),
            Emojicon.fromCodePoint(0x1a5a8),
//            Emojicon.fromCodePoint(0x1a5a9),

            Emojicon.fromCodePoint(0x1a5b0),
            Emojicon.fromCodePoint(0x1a5b1),
            Emojicon.fromCodePoint(0x1a5b2),
            Emojicon.fromCodePoint(0x1a5b3),
            Emojicon.fromCodePoint(0x1a5b4),
            Emojicon.fromCodePoint(0x1a5b5),
            Emojicon.fromCodePoint(0x1a5b6),
            Emojicon.fromCodePoint(0x1a5b7),
            Emojicon.fromCodePoint(0x1a5b8),
            Emojicon.fromCodePoint(0x1a5b9),

            Emojicon.fromCodePoint(0x1a5c0),
            Emojicon.fromCodePoint(0x1a5c1),
            Emojicon.fromCodePoint(0x1a5c2),
            Emojicon.fromCodePoint(0x1a5c3),
            Emojicon.fromCodePoint(0x1a5c4),
            Emojicon.fromCodePoint(0x1a5c5),
            Emojicon.fromCodePoint(0x1a5c6),


    };
}
